# Generated by Django 4.1.1 on 2022-09-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_customer_options_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['placed_at'], 'permissions': [('cancel_order', 'Can cancel order')]},
        ),
    ]
