# Generated by Django 4.0.6 on 2022-09-09 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['label']},
        ),
    ]
